name: Push

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      no_push:
        description: 'Test only, without pushing to prod'
        type: boolean
        default: true

jobs:
  cog-safe-push:
    runs-on: ubuntu-latest-4-cores

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Cog
      run: |
        #sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
        # this is the latest main which has new base images for torch 2.4.0
        sudo curl -o /usr/local/bin/cog -L "https://storage.googleapis.com/andreas-scratch-public/cog-26208388-linux-x86_64"
        sudo chmod +x /usr/local/bin/cog

    - name: cog login
      run: |
        echo ${{ secrets.COG_TOKEN }} | cog login --token-stdin

    - name: Install cog-safe-push
      run: |
        pip install git+https://github.com/replicate/cog-safe-push.git

    - name: Run cog-safe-push to test the trainer and predictor and optionally push to production
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: |
        cog-safe-push -vv ${{ github.event.inputs.no_push == 'true' && '--no-push' || '' }}
